/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1MetaRouteImport } from './routes/api/public/v1/meta'
import { Route as ApiPublicV1OrdersIndexRouteImport } from './routes/api/public/v1/orders/index'
import { Route as ApiPublicV1OrdersIdIndexRouteImport } from './routes/api/public/v1/orders/$id/index'
import { Route as ApiPublicV1OrdersIdCancelRouteImport } from './routes/api/public/v1/orders/$id/cancel'
import { Route as ApiPublicV1OrdersIdItemsRouteImport } from './routes/api/public/v1/orders/$id/items'
import { Route as ApiPublicV1OrdersIdReshipRouteImport } from './routes/api/public/v1/orders/$id/reship'
import { Route as ApiPublicV1OrdersIdShipmentsRouteImport } from './routes/api/public/v1/orders/$id/shipments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MetaRoute = ApiPublicV1MetaRouteImport.update({
  id: '/api/public/v1/meta',
  path: '/api/public/v1/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrdersIndexRoute = ApiPublicV1OrdersIndexRouteImport.update({
  id: '/api/public/v1/orders/',
  path: '/api/public/v1/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrdersIdIndexRoute =
  ApiPublicV1OrdersIdIndexRouteImport.update({
    id: '/api/public/v1/orders/$id/',
    path: '/api/public/v1/orders/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersIdCancelRoute =
  ApiPublicV1OrdersIdCancelRouteImport.update({
    id: '/api/public/v1/orders/$id/cancel',
    path: '/api/public/v1/orders/$id/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersIdItemsRoute =
  ApiPublicV1OrdersIdItemsRouteImport.update({
    id: '/api/public/v1/orders/$id/items',
    path: '/api/public/v1/orders/$id/items',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersIdReshipRoute =
  ApiPublicV1OrdersIdReshipRouteImport.update({
    id: '/api/public/v1/orders/$id/reship',
    path: '/api/public/v1/orders/$id/reship',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrdersIdShipmentsRoute =
  ApiPublicV1OrdersIdShipmentsRouteImport.update({
    id: '/api/public/v1/orders/$id/shipments',
    path: '/api/public/v1/orders/$id/shipments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/meta': typeof ApiPublicV1MetaRoute
  '/api/public/v1/orders/': typeof ApiPublicV1OrdersIndexRoute
  '/api/public/v1/orders/$id/cancel': typeof ApiPublicV1OrdersIdCancelRoute
  '/api/public/v1/orders/$id/items': typeof ApiPublicV1OrdersIdItemsRoute
  '/api/public/v1/orders/$id/reship': typeof ApiPublicV1OrdersIdReshipRoute
  '/api/public/v1/orders/$id/shipments': typeof ApiPublicV1OrdersIdShipmentsRoute
  '/api/public/v1/orders/$id/': typeof ApiPublicV1OrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/meta': typeof ApiPublicV1MetaRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersIndexRoute
  '/api/public/v1/orders/$id/cancel': typeof ApiPublicV1OrdersIdCancelRoute
  '/api/public/v1/orders/$id/items': typeof ApiPublicV1OrdersIdItemsRoute
  '/api/public/v1/orders/$id/reship': typeof ApiPublicV1OrdersIdReshipRoute
  '/api/public/v1/orders/$id/shipments': typeof ApiPublicV1OrdersIdShipmentsRoute
  '/api/public/v1/orders/$id': typeof ApiPublicV1OrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/meta': typeof ApiPublicV1MetaRoute
  '/api/public/v1/orders/': typeof ApiPublicV1OrdersIndexRoute
  '/api/public/v1/orders/$id/cancel': typeof ApiPublicV1OrdersIdCancelRoute
  '/api/public/v1/orders/$id/items': typeof ApiPublicV1OrdersIdItemsRoute
  '/api/public/v1/orders/$id/reship': typeof ApiPublicV1OrdersIdReshipRoute
  '/api/public/v1/orders/$id/shipments': typeof ApiPublicV1OrdersIdShipmentsRoute
  '/api/public/v1/orders/$id/': typeof ApiPublicV1OrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/v1/health'
    | '/api/public/v1/meta'
    | '/api/public/v1/orders/'
    | '/api/public/v1/orders/$id/cancel'
    | '/api/public/v1/orders/$id/items'
    | '/api/public/v1/orders/$id/reship'
    | '/api/public/v1/orders/$id/shipments'
    | '/api/public/v1/orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/v1/health'
    | '/api/public/v1/meta'
    | '/api/public/v1/orders'
    | '/api/public/v1/orders/$id/cancel'
    | '/api/public/v1/orders/$id/items'
    | '/api/public/v1/orders/$id/reship'
    | '/api/public/v1/orders/$id/shipments'
    | '/api/public/v1/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/api/public/v1/health'
    | '/api/public/v1/meta'
    | '/api/public/v1/orders/'
    | '/api/public/v1/orders/$id/cancel'
    | '/api/public/v1/orders/$id/items'
    | '/api/public/v1/orders/$id/reship'
    | '/api/public/v1/orders/$id/shipments'
    | '/api/public/v1/orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1MetaRoute: typeof ApiPublicV1MetaRoute
  ApiPublicV1OrdersIndexRoute: typeof ApiPublicV1OrdersIndexRoute
  ApiPublicV1OrdersIdCancelRoute: typeof ApiPublicV1OrdersIdCancelRoute
  ApiPublicV1OrdersIdItemsRoute: typeof ApiPublicV1OrdersIdItemsRoute
  ApiPublicV1OrdersIdReshipRoute: typeof ApiPublicV1OrdersIdReshipRoute
  ApiPublicV1OrdersIdShipmentsRoute: typeof ApiPublicV1OrdersIdShipmentsRoute
  ApiPublicV1OrdersIdIndexRoute: typeof ApiPublicV1OrdersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/meta': {
      id: '/api/public/v1/meta'
      path: '/api/public/v1/meta'
      fullPath: '/api/public/v1/meta'
      preLoaderRoute: typeof ApiPublicV1MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/': {
      id: '/api/public/v1/orders/'
      path: '/api/public/v1/orders'
      fullPath: '/api/public/v1/orders/'
      preLoaderRoute: typeof ApiPublicV1OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$id/': {
      id: '/api/public/v1/orders/$id/'
      path: '/api/public/v1/orders/$id'
      fullPath: '/api/public/v1/orders/$id/'
      preLoaderRoute: typeof ApiPublicV1OrdersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$id/cancel': {
      id: '/api/public/v1/orders/$id/cancel'
      path: '/api/public/v1/orders/$id/cancel'
      fullPath: '/api/public/v1/orders/$id/cancel'
      preLoaderRoute: typeof ApiPublicV1OrdersIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$id/items': {
      id: '/api/public/v1/orders/$id/items'
      path: '/api/public/v1/orders/$id/items'
      fullPath: '/api/public/v1/orders/$id/items'
      preLoaderRoute: typeof ApiPublicV1OrdersIdItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$id/reship': {
      id: '/api/public/v1/orders/$id/reship'
      path: '/api/public/v1/orders/$id/reship'
      fullPath: '/api/public/v1/orders/$id/reship'
      preLoaderRoute: typeof ApiPublicV1OrdersIdReshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/$id/shipments': {
      id: '/api/public/v1/orders/$id/shipments'
      path: '/api/public/v1/orders/$id/shipments'
      fullPath: '/api/public/v1/orders/$id/shipments'
      preLoaderRoute: typeof ApiPublicV1OrdersIdShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1MetaRoute: ApiPublicV1MetaRoute,
  ApiPublicV1OrdersIndexRoute: ApiPublicV1OrdersIndexRoute,
  ApiPublicV1OrdersIdCancelRoute: ApiPublicV1OrdersIdCancelRoute,
  ApiPublicV1OrdersIdItemsRoute: ApiPublicV1OrdersIdItemsRoute,
  ApiPublicV1OrdersIdReshipRoute: ApiPublicV1OrdersIdReshipRoute,
  ApiPublicV1OrdersIdShipmentsRoute: ApiPublicV1OrdersIdShipmentsRoute,
  ApiPublicV1OrdersIdIndexRoute: ApiPublicV1OrdersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
