/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1MetaRouteImport } from './routes/api/public/v1/meta'
import { Route as ApiPublicV1OrdersIndexRouteImport } from './routes/api/public/v1/orders/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MetaRoute = ApiPublicV1MetaRouteImport.update({
  id: '/api/public/v1/meta',
  path: '/api/public/v1/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrdersIndexRoute = ApiPublicV1OrdersIndexRouteImport.update({
  id: '/api/public/v1/orders/',
  path: '/api/public/v1/orders/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/meta': typeof ApiPublicV1MetaRoute
  '/api/public/v1/orders/': typeof ApiPublicV1OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/meta': typeof ApiPublicV1MetaRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/meta': typeof ApiPublicV1MetaRoute
  '/api/public/v1/orders/': typeof ApiPublicV1OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/v1/health'
    | '/api/public/v1/meta'
    | '/api/public/v1/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/v1/health'
    | '/api/public/v1/meta'
    | '/api/public/v1/orders'
  id:
    | '__root__'
    | '/'
    | '/api/public/v1/health'
    | '/api/public/v1/meta'
    | '/api/public/v1/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1MetaRoute: typeof ApiPublicV1MetaRoute
  ApiPublicV1OrdersIndexRoute: typeof ApiPublicV1OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/meta': {
      id: '/api/public/v1/meta'
      path: '/api/public/v1/meta'
      fullPath: '/api/public/v1/meta'
      preLoaderRoute: typeof ApiPublicV1MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders/': {
      id: '/api/public/v1/orders/'
      path: '/api/public/v1/orders'
      fullPath: '/api/public/v1/orders/'
      preLoaderRoute: typeof ApiPublicV1OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1MetaRoute: ApiPublicV1MetaRoute,
  ApiPublicV1OrdersIndexRoute: ApiPublicV1OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
